+incdir+./rtl/include
+incdir+./rtl/include/common/xbar
+incdir+./rtl/include/memory/scratchpad
+incdir+./rtl/modules
+incdir+./rtl/modules/common
+incdir+./rtl/modules/common/general
rtl/include/common/xbar/xbar_pkg.sv
rtl/include/common/xbar/xbar_if.sv
rtl/modules/common/general/sync_fifo.sv
rtl/include/memory/scratchpad/scpad_pkg.sv
rtl/include/memory/scratchpad/scpad_if.sv
rtl/modules/memory/scratchpad/wxbar.sv
rtl/modules/memory/scratchpad/rxbar.sv
rtl/modules/memory/scratchpad/head.sv
rtl/modules/memory/scratchpad/body.sv
rtl/modules/memory/scratchpad/tail.sv
rtl/modules/memory/scratchpad/dram_request_queue.sv
rtl/modules/memory/scratchpad/dram_write_latch.sv
rtl/modules/memory/scratchpad/sram_write_latch.sv
rtl/modules/memory/scratchpad/scpad_cntrl.sv
rtl/modules/memory/scratchpad/backend.sv
tb/unit/memory/scratchpad/wxbar.sv
tb/unit/memory/scratchpad/rxbar.sv
tb/unit/memory/scratchpad/head.sv
tb/unit/memory/scratchpad/body.sv
tb/unit/memory/scratchpad/tail.sv
tb/unit/memory/scratchpad/spad_cntrl.sv
tb/unit/memory/scratchpad/frontend.sv
tb/unit/memory/scratchpad/backend_tb.sv
