from pathlib import Path
import os
import struct
import sys
import argparse

# ---------------------------------------------------------------------
# File paths
# ---------------------------------------------------------------------
PATH_TO_PKG_FILE = "tb/unit/systolic_array/systolic_array_tb_pkg.sv"
ATALLA_ROOT = os.getenv("ATALLA_ROOT")
if ATALLA_ROOT is None:
    raise RuntimeError("ATALLA_ROOT env variable is not defined")
ATALLA_ROOT = Path(ATALLA_ROOT).expanduser().resolve()
PATH_TO_INPUT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_input.csv"
PATH_TO_EXPECTED_RESULT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_expected_result.csv"
PATH_TO_RESULT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_result.csv"

# ---------------------------------------------------------------------
# Systolic array params
# ---------------------------------------------------------------------
array_dim = 32
data_width = 16
version = "MEISSA"

# ---------------------------------------------------------------------
# Create tb package file
# ---------------------------------------------------------------------
def create_tb_pkg():
    with open(ATALLA_ROOT / PATH_TO_PKG_FILE, "w") as pkg:
        pkg.write("// This file is auto generated by scripts/systolic_array/gen_systolic_array_pkg.py \n\n")

        pkg.write(f"package systolic_array_tb_pkg;\n")
        pkg.write(f"// Local params contains path to input and output files for file reading\n")
        pkg.write(f"localparam string PATH_TO_PROJ = \"{ATALLA_ROOT}\";\n")
        pkg.write(f"localparam string PATH_TO_INPUT = \"{PATH_TO_INPUT}\";\n")
        pkg.write(f"localparam string PATH_TO_EXPECTED_RESULT = \"{PATH_TO_EXPECTED_RESULT}\";\n")
        pkg.write(f"localparam string PATH_TO_RESULT = \"{PATH_TO_RESULT}\";\n")
        pkg.write(f"\n")

        pkg.write(f"// Systolic array parameters\n")
        # pkg.write(f"parameter int LATENCY = {latency};\n")
        pkg.write(f"parameter int ARRAY_DIM = {array_dim};\n")
        pkg.write(f"parameter int DATA_WIDTH = {data_width};\n")
        pkg.write(f"// Might need this for variable array size?\n")
        pkg.write(f"// parameter int ARRAY_WIDTH = {array_dim};\n")
        pkg.write(f"// parameter int ARRAY_HEIGHT = {array_dim};\n")
        pkg.write(f"// parameter int ARRAY_HEIGHT = {array_dim};\n")
        pkg.write(f"parameter string VERSION = \"{version}\";\n")

        pkg.write(f"endpackage\n")
    print(f"Generated tb package file to {ATALLA_ROOT}/{PATH_TO_PKG_FILE}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", type=str, help="Systolic Array Design Version")

    args = parser.parse_args()

    version = args.version

    create_tb_pkg()

