onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /clos_tb/clk
add wave -noupdate /clos_tb/n_rst
add wave -noupdate /clos_tb/xif/en
add wave -noupdate /clos_tb/DUT/out_perm
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/input_module[7]} -radix decimal} {{/clos_tb/DUT/input_module[6]} -radix decimal} {{/clos_tb/DUT/input_module[5]} -radix decimal} {{/clos_tb/DUT/input_module[4]} -radix decimal} {{/clos_tb/DUT/input_module[3]} -radix decimal} {{/clos_tb/DUT/input_module[2]} -radix decimal} {{/clos_tb/DUT/input_module[1]} -radix decimal} {{/clos_tb/DUT/input_module[0]} -radix decimal}} -subitemconfig {{/clos_tb/DUT/input_module[7]} {-height 16 -radix decimal} {/clos_tb/DUT/input_module[6]} {-height 16 -radix decimal} {/clos_tb/DUT/input_module[5]} {-height 16 -radix decimal} {/clos_tb/DUT/input_module[4]} {-height 16 -radix decimal} {/clos_tb/DUT/input_module[3]} {-height 16 -radix decimal} {/clos_tb/DUT/input_module[2]} {-height 16 -radix decimal} {/clos_tb/DUT/input_module[1]} {-height 16 -radix decimal} {/clos_tb/DUT/input_module[0]} {-height 16 -radix decimal}} /clos_tb/DUT/input_module
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/center_module[3]} -radix unsigned} {{/clos_tb/DUT/center_module[2]} -radix unsigned} {{/clos_tb/DUT/center_module[1]} -radix unsigned} {{/clos_tb/DUT/center_module[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/center_module[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/center_module[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/center_module[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/center_module[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/center_module
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/output_module[7]} -radix unsigned} {{/clos_tb/DUT/output_module[6]} -radix unsigned} {{/clos_tb/DUT/output_module[5]} -radix unsigned} {{/clos_tb/DUT/output_module[4]} -radix unsigned} {{/clos_tb/DUT/output_module[3]} -radix unsigned} {{/clos_tb/DUT/output_module[2]} -radix unsigned} {{/clos_tb/DUT/output_module[1]} -radix unsigned} {{/clos_tb/DUT/output_module[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/output_module[7]} {-radix unsigned} {/clos_tb/DUT/output_module[6]} {-radix unsigned} {/clos_tb/DUT/output_module[5]} {-radix unsigned} {/clos_tb/DUT/output_module[4]} {-radix unsigned} {/clos_tb/DUT/output_module[3]} {-radix unsigned} {/clos_tb/DUT/output_module[2]} {-radix unsigned} {/clos_tb/DUT/output_module[1]} {-radix unsigned} {/clos_tb/DUT/output_module[0]} {-radix unsigned}} /clos_tb/DUT/output_module
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/n_center_module[3]} -radix unsigned} {{/clos_tb/DUT/n_center_module[2]} -radix unsigned} {{/clos_tb/DUT/n_center_module[1]} -radix unsigned} {{/clos_tb/DUT/n_center_module[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/n_center_module[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_center_module[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_center_module[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_center_module[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/n_center_module
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/n_output_module[7]} -radix unsigned} {{/clos_tb/DUT/n_output_module[6]} -radix unsigned} {{/clos_tb/DUT/n_output_module[5]} -radix unsigned} {{/clos_tb/DUT/n_output_module[4]} -radix unsigned} {{/clos_tb/DUT/n_output_module[3]} -radix unsigned} {{/clos_tb/DUT/n_output_module[2]} -radix unsigned} {{/clos_tb/DUT/n_output_module[1]} -radix unsigned} {{/clos_tb/DUT/n_output_module[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/n_output_module[7]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_module[6]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_module[5]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_module[4]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_module[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_module[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_module[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_module[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/n_output_module
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/input_perm[7]} -radix unsigned} {{/clos_tb/DUT/input_perm[6]} -radix unsigned} {{/clos_tb/DUT/input_perm[5]} -radix unsigned} {{/clos_tb/DUT/input_perm[4]} -radix unsigned} {{/clos_tb/DUT/input_perm[3]} -radix unsigned} {{/clos_tb/DUT/input_perm[2]} -radix unsigned} {{/clos_tb/DUT/input_perm[1]} -radix unsigned} {{/clos_tb/DUT/input_perm[0]} -radix binary -childformat {{{/clos_tb/DUT/input_perm[0][3]} -radix unsigned} {{/clos_tb/DUT/input_perm[0][2]} -radix unsigned} {{/clos_tb/DUT/input_perm[0][1]} -radix unsigned} {{/clos_tb/DUT/input_perm[0][0]} -radix unsigned}}}} -subitemconfig {{/clos_tb/DUT/input_perm[7]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[6]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[5]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[4]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[0]} {-height 16 -radix binary -childformat {{{/clos_tb/DUT/input_perm[0][3]} -radix unsigned} {{/clos_tb/DUT/input_perm[0][2]} -radix unsigned} {{/clos_tb/DUT/input_perm[0][1]} -radix unsigned} {{/clos_tb/DUT/input_perm[0][0]} -radix unsigned}}} {/clos_tb/DUT/input_perm[0][3]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[0][2]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[0][1]} {-height 16 -radix unsigned} {/clos_tb/DUT/input_perm[0][0]} {-height 16 -radix unsigned}} /clos_tb/DUT/input_perm
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/center_perm[3]} -radix unsigned} {{/clos_tb/DUT/center_perm[2]} -radix unsigned} {{/clos_tb/DUT/center_perm[1]} -radix unsigned} {{/clos_tb/DUT/center_perm[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/center_perm[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/center_perm[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/center_perm[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/center_perm[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/center_perm
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/output_perm[7]} -radix unsigned} {{/clos_tb/DUT/output_perm[6]} -radix unsigned} {{/clos_tb/DUT/output_perm[5]} -radix unsigned} {{/clos_tb/DUT/output_perm[4]} -radix unsigned} {{/clos_tb/DUT/output_perm[3]} -radix unsigned} {{/clos_tb/DUT/output_perm[2]} -radix unsigned} {{/clos_tb/DUT/output_perm[1]} -radix unsigned} {{/clos_tb/DUT/output_perm[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/output_perm[7]} {-height 16 -radix unsigned} {/clos_tb/DUT/output_perm[6]} {-height 16 -radix unsigned} {/clos_tb/DUT/output_perm[5]} {-height 16 -radix unsigned} {/clos_tb/DUT/output_perm[4]} {-height 16 -radix unsigned} {/clos_tb/DUT/output_perm[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/output_perm[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/output_perm[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/output_perm[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/output_perm
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/n_center_perm[3]} -radix unsigned} {{/clos_tb/DUT/n_center_perm[2]} -radix unsigned} {{/clos_tb/DUT/n_center_perm[1]} -radix unsigned} {{/clos_tb/DUT/n_center_perm[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/n_center_perm[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_center_perm[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_center_perm[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_center_perm[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/n_center_perm
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/n_output_perm[7]} -radix unsigned} {{/clos_tb/DUT/n_output_perm[6]} -radix unsigned} {{/clos_tb/DUT/n_output_perm[5]} -radix unsigned} {{/clos_tb/DUT/n_output_perm[4]} -radix unsigned} {{/clos_tb/DUT/n_output_perm[3]} -radix unsigned} {{/clos_tb/DUT/n_output_perm[2]} -radix unsigned} {{/clos_tb/DUT/n_output_perm[1]} -radix unsigned} {{/clos_tb/DUT/n_output_perm[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/n_output_perm[7]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_perm[6]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_perm[5]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_perm[4]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_perm[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_perm[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_perm[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/n_output_perm[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/n_output_perm
add wave -noupdate -radix unsigned /clos_tb/DUT/lsb
add wave -noupdate -radix unsigned -childformat {{{/clos_tb/DUT/num_counter[7]} -radix unsigned} {{/clos_tb/DUT/num_counter[6]} -radix unsigned} {{/clos_tb/DUT/num_counter[5]} -radix unsigned} {{/clos_tb/DUT/num_counter[4]} -radix unsigned} {{/clos_tb/DUT/num_counter[3]} -radix unsigned} {{/clos_tb/DUT/num_counter[2]} -radix unsigned} {{/clos_tb/DUT/num_counter[1]} -radix unsigned} {{/clos_tb/DUT/num_counter[0]} -radix unsigned}} -subitemconfig {{/clos_tb/DUT/num_counter[7]} {-height 16 -radix unsigned} {/clos_tb/DUT/num_counter[6]} {-height 16 -radix unsigned} {/clos_tb/DUT/num_counter[5]} {-height 16 -radix unsigned} {/clos_tb/DUT/num_counter[4]} {-height 16 -radix unsigned} {/clos_tb/DUT/num_counter[3]} {-height 16 -radix unsigned} {/clos_tb/DUT/num_counter[2]} {-height 16 -radix unsigned} {/clos_tb/DUT/num_counter[1]} {-height 16 -radix unsigned} {/clos_tb/DUT/num_counter[0]} {-height 16 -radix unsigned}} /clos_tb/DUT/num_counter
add wave -noupdate -radix unsigned /clos_tb/DUT/om_dest
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {19 ns}
