`timescale 1ns / 10ps
`include "alu_control_if.sv"

module alu_control_wrapper_tb;

    parameter PERIOD = 2;
    logic CLK = 0, nRST;
    always #(PERIOD/2) CLK++;
    string casename;

    alu_control_if mainport ();

    alu_control DUT (.CLK(CLK), .nRST(nRST), .portmap(mainport));


    initial begin
        casename = "rst";
        mainport.rs1_value = 32'b0;
        mainport.rs2_value = 32'b0;
        mainport.rdIn = 8'b0;
        mainport.rs1_idx = 8'b0;
        mainport.pc = 32'b0;
        mainport.incr7 = 32'b0;
        mainport.imm = 32'b0;
        mainport.op = 7'b0;
        mainport.valid_in = 1'b0;
        mainport.ready_out = 1'b1;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b0;
        nRST = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        nRST = 1'b1;

        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        casename = "alu add";
        mainport.rs1_value = 32'd100;
        mainport.rs2_value = 32'd500;
        mainport.rdIn = 8'd39;
        mainport.rs1_idx = 8'b0;
        mainport.pc = 32'b0;
        mainport.incr7 = 32'b0;
        mainport.imm = 32'b0;
        mainport.op = 7'b0000001;
        mainport.valid_in = 1'b1;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b1;
        mainport.control_valid = 1'b0;
        @(negedge CLK);
        mainport.rs1_value = 32'b0;
        mainport.rs2_value = 32'b0;
        mainport.rdIn = 8'b0;
        mainport.rs1_idx = 8'b0;
        mainport.pc = 32'b0;
        mainport.incr7 = 32'b0;
        mainport.imm = 32'b0;
        mainport.op = 7'b0;
        mainport.valid_in = 1'b0;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        casename = "no branch";
        mainport.rs1_value = 32'd100;
        mainport.rs2_value = 32'd500;
        mainport.rdIn = 8'd0;
        mainport.rs1_idx = 8'd40;
        mainport.pc = 32'h0000FF00;
        mainport.incr7 = 32'd1;
        mainport.imm = 32'hFF;
        mainport.op = 7'b0100011;
        mainport.valid_in = 1'b1;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b1;
        @(negedge CLK);
        mainport.rs1_value = 32'b0;
        mainport.rs2_value = 32'b0;
        mainport.rdIn = 8'b0;
        mainport.rs1_idx = 8'b0;
        mainport.pc = 32'b0;
        mainport.incr7 = 32'b0;
        mainport.imm = 32'b0;
        mainport.op = 7'b0;
        mainport.valid_in = 1'b0;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        casename = "branch";
        mainport.rs1_value = 32'd100;
        mainport.rs2_value = 32'd100;
        mainport.rdIn = 8'd0;
        mainport.rs1_idx = 8'd40;
        mainport.pc = 32'h0000FF00;
        mainport.incr7 = 32'd1;
        mainport.imm = 32'hFF;
        mainport.op = 7'b0100011;
        mainport.valid_in = 1'b1;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b1;
        @(negedge CLK);
        mainport.rs1_value = 32'b0;
        mainport.rs2_value = 32'b0;
        mainport.rdIn = 8'b0;
        mainport.rs1_idx = 8'b0;
        mainport.pc = 32'b0;
        mainport.incr7 = 32'b0;
        mainport.imm = 32'b0;
        mainport.op = 7'b0;
        mainport.valid_in = 1'b0;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        casename = "JAL";
        mainport.rs1_value = 32'd0;
        mainport.rs2_value = 32'd0;
        mainport.rdIn = 8'd24;
        mainport.rs1_idx = 8'd00;
        mainport.pc = 32'h0000FF00;
        mainport.incr7 = 32'd1;
        mainport.imm = 32'hFF;
        mainport.op = 7'b0101011;
        mainport.valid_in = 1'b1;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b1;
        @(negedge CLK);
        mainport.rs1_value = 32'b0;
        mainport.rs2_value = 32'b0;
        mainport.rdIn = 8'b0;
        mainport.rs1_idx = 8'b0;
        mainport.pc = 32'b0;
        mainport.incr7 = 32'b0;
        mainport.imm = 32'b0;
        mainport.op = 7'b0;
        mainport.valid_in = 1'b0;
        mainport.ready_out = 1'b0;
        mainport.alu_valid = 1'b0;
        mainport.control_valid = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        $display("DONE");
        $finish;
    end


endmodule