`timescale 1ns / 10ps
`include "bfD_sD_bfInt_intBF_if.sv"

module div_bf_scalar_convert_wrapper_tb;

    parameter PERIOD = 2;
    logic CLK = 0, nRST;
    always #(PERIOD/2) CLK++;
    string casename;

    bfD_sD_bfInt_intBF_if mainport ();

    div_bf_scalar_convert_wrapper DUT (.clk(CLK), .nRST(nRST), .portmap(mainport));


    initial begin
        casename = "rst";
        mainport.input1 = 32'b0;
        mainport.input2 = 32'b0;
        mainport.bf_div = 1'b0;
        mainport.s_div = 1'b0;
        mainport.s_mod = 1'b0;
        mainport.BF_to_int = 1'b0;
        mainport.int_to_BF = 1'b0;
        mainport.rdIn = 8'b0;
        mainport.valid_in = 1'b0;
        mainport.ready_out = 1'b1;
        nRST = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        nRST = 1'b1;

        casename = "bf_div, stall";
        mainport.input1 = 32'h0000421c;
        mainport.input2 = 32'h00004160;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.bf_div = 1'b1;
        mainport.ready_out = 1'b0;
        @(negedge CLK);
        mainport.input1 = 32'h0;
        mainport.input2 = 32'h0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.bf_div = 1'b0;
        mainport.ready_out = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        casename = "bf_div, stall";
        mainport.valid_in = 1'b1;
        mainport.input1 = 32'h000044ac;
        mainport.input2 = 32'h00004100;
        mainport.rdIn = 8'd28;
        mainport.ready_out = 1'b0;
        mainport.bf_div = 1'b1;
        @(negedge CLK);
        mainport.valid_in = 1'b0;
        mainport.input1 = 32'h0;
        mainport.input2 = 32'h0;
        mainport.rdIn = 8'd0;
        mainport.bf_div = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(negedge CLK);
        @(negedge CLK);
        @(negedge CLK);
        casename = "bf_div, no stall";
        mainport.valid_in = 1'b1;
        mainport.input1 = 32'h000047f1;
        mainport.input2 = 32'h00004617;
        mainport.rdIn = 8'd28;
        mainport.ready_out = 1'b1;
        mainport.bf_div = 1'b1;
        @(negedge CLK);
        mainport.valid_in = 1'b0;
        mainport.input1 = 32'h0;
        mainport.input2 = 32'h0;
        mainport.rdIn = 8'd0;
        mainport.bf_div = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        casename = "bf to int, no stall";
        mainport.input1 = 32'h0000421c;
        mainport.input2 = 32'h00000000;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.BF_to_int = 1'b1;
        mainport.ready_out = 1'b1;
        @(negedge CLK);
        mainport.input1 = 32'h0;
        mainport.input2 = 32'h0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.BF_to_int = 1'b0;
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        casename = "bf to int, stall";
        mainport.input1 = 32'h0000c29c;
        mainport.input2 = 32'h00000000;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.BF_to_int = 1'b1;
        mainport.ready_out = 1'b0;
        @(negedge CLK);
        mainport.input1 = 32'h0;
        mainport.input2 = 32'h0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.BF_to_int = 1'b0;
        mainport.ready_out = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        casename = "int to bf, no stall";
        mainport.input1 = 32'h0000421c;
        mainport.input2 = 32'h00000000;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.int_to_BF = 1'b1;
        mainport.ready_out = 1'b1;
        @(negedge CLK);
        mainport.input1 = 32'h0;
        mainport.input2 = 32'h0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.int_to_BF = 1'b0;
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        casename = "int to bf, stall";
        mainport.input1 = 32'h0000c29c;
        mainport.input2 = 32'h00000000;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.int_to_BF = 1'b1;
        mainport.ready_out = 1'b0;
        @(negedge CLK);
        mainport.input1 = 32'h0;
        mainport.input2 = 32'h0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.int_to_BF = 1'b0;
        mainport.ready_out = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        casename = "scalar div, no stall";
        mainport.input1 = 32'd125;
        mainport.input2 = 32'd25;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.s_div = 1'b1;
        mainport.ready_out = 1'b1;
        @(negedge CLK);
        mainport.input1 = 32'd0;
        mainport.input2 = 32'd0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.s_div = 1'b0;
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        casename = "scalar div, stall";
        mainport.input1 = 32'd125;
        mainport.input2 = 32'hFFFFFFE7;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.s_div = 1'b1;
        mainport.ready_out = 1'b0;
        @(negedge CLK);
        mainport.input1 = 32'd0;
        mainport.input2 = 32'd0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.s_div = 1'b0;
        mainport.ready_out = 1'b0;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        casename = "scalar mod";
        mainport.input1 = 32'd12345;
        mainport.input2 = 32'd17;
        mainport.valid_in = 1'b1;
        mainport.rdIn = 8'd12;
        mainport.s_mod = 1'b1;
        mainport.ready_out = 1'b1;
        @(negedge CLK);
        mainport.input1 = 32'd0;
        mainport.input2 = 32'd0;
        mainport.valid_in = 1'b0;
        mainport.rdIn = 8'd0;
        mainport.s_mod = 1'b0;
        mainport.ready_out = 1'b1;
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(posedge CLK);
        @(negedge CLK);

        $display("DONE");
        $finish;
    end


endmodule