Frontend:
  impl: GEM5
  clock_ratio: 2    # tick every 2 ramulator_tick calls → 800 MHz = SV core clock

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1    # tick every ramulator_tick call → 1600 MHz = DDR4-3200 memory clock

  DRAM:
    impl: DDR4
    org:
      preset: DDR4_8Gb_x16
      channel: 1
      rank: 2
    timing:
      preset: DDR4_3200W

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 16
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
