###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID asicfab.ecn.purdue.edu)
#  Generated on:      Mon Nov 10 13:10:34 2025
#  Design:            wtm_bf16
#  Command:           check_design -out_file reports/prects/check.design.tcl -type {timing place opt}
###############################################################
#Design Check : place (1)
# --------------------------------------------------------------------------------------
# Message: %d unplaced pins detected, please place them properly or add "set_db place_global_place_io_pins true" to place them automatically in the flow.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks place CHKPLC-51 {
  severity warning
  count 1
  violations {
    {52}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Maximum transition %.3f is too small compared to maximum transition threshold %.3f, this would result in excessive buffering.
#    Help: 
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-2908 {
  severity warning
  count 1
  violations {
    {-0.000 0.292}
  }
}
#Design Check : opt (37)
# --------------------------------------------------------------------------------------
# Message: %s : Net has unplaced terms or is connected to uplaced instances in design.
#    Help: This warning message is issued during optimization if there are nets connected to any unplaced I/O pins or unplaced instances in the design. The unplaced instances can be reported by running check_place command and unplaced I/O's can be reported by running 'check_pin_assignment  -report_violating_pin' command.Once these issues are fixed the warning message will not be reported.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-665 {
  severity warning
  count 37
  violations {
    {clk}
    {rst}
    {Ain[15]}
    {Ain[14]}
    {Ain[13]}
    {Ain[12]}
    {Ain[11]}
    {Ain[10]}
    {Ain[9]}
    {Ain[8]}
    {Ain[7]}
    {Ain[6]}
    {Ain[5]}
    {Ain[4]}
    {Ain[3]}
    {Ain[2]}
    {Ain[1]}
    {Ain[0]}
    {Bin[15]}
    {Bin[14]}
    {Bin[13]}
    {Bin[12]}
    {Bin[11]}
    {Bin[10]}
    {Bin[9]}
    {Bin[8]}
    {Bin[7]}
    {Bin[6]}
    {Bin[5]}
    {Bin[4]}
    {Bin[3]}
    {Bin[2]}
    {Bin[1]}
    {Bin[0]}
    {Sum[15]}
    {Error[1]}
    {Error[0]}
  }
}
#Design Check : opt (1)
# --------------------------------------------------------------------------------------
# Message: Running power optimization flow with leakage to dynamic ratio of %f but without activity file loaded.
#    Help: Please provide activity file.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-7264 {
  severity warning
  count 1
  violations {
    {0.800000}
  }
}
#Design Check : opt (120)
# --------------------------------------------------------------------------------------
# Message: The <%s> net <%s> has an issue with RC extraction : "Empty RC". Issue found in view <%s> and rc corner <%s>
#    Help: This error is encountered while checking the integrity of the RC data for performing optimization. To resolve this error, check the routing of the net and verify that the net is fully routed and connected. Re-run a full RC extraction using the extract_rc command.
# --------------------------------------------------------------------------------------
dict set design_checks opt IMPOPT-7287 {
  severity warning
  count 120
  violations {
    {clock clk view_1p2_25 rc_worst_25}
    {data rst view_1p2_25 rc_worst_25}
    {data Ain[15] view_1p2_25 rc_worst_25}
    {data Ain[14] view_1p2_25 rc_worst_25}
    {data Ain[13] view_1p2_25 rc_worst_25}
    {data Ain[12] view_1p2_25 rc_worst_25}
    {data Ain[11] view_1p2_25 rc_worst_25}
    {data Ain[10] view_1p2_25 rc_worst_25}
    {data Ain[9] view_1p2_25 rc_worst_25}
    {data Ain[8] view_1p2_25 rc_worst_25}
    {data Ain[7] view_1p2_25 rc_worst_25}
    {data Ain[6] view_1p2_25 rc_worst_25}
    {data Ain[5] view_1p2_25 rc_worst_25}
    {data Ain[4] view_1p2_25 rc_worst_25}
    {data Ain[3] view_1p2_25 rc_worst_25}
    {data Ain[2] view_1p2_25 rc_worst_25}
    {data Ain[1] view_1p2_25 rc_worst_25}
    {data Ain[0] view_1p2_25 rc_worst_25}
    {data Bin[15] view_1p2_25 rc_worst_25}
    {data Bin[14] view_1p2_25 rc_worst_25}
    {data Bin[13] view_1p2_25 rc_worst_25}
    {data Bin[12] view_1p2_25 rc_worst_25}
    {data Bin[11] view_1p2_25 rc_worst_25}
    {data Bin[10] view_1p2_25 rc_worst_25}
    {data Bin[9] view_1p2_25 rc_worst_25}
    {data Bin[8] view_1p2_25 rc_worst_25}
    {data Bin[7] view_1p2_25 rc_worst_25}
    {data Bin[6] view_1p2_25 rc_worst_25}
    {data Bin[5] view_1p2_25 rc_worst_25}
    {data Bin[4] view_1p2_25 rc_worst_25}
    {data Bin[3] view_1p2_25 rc_worst_25}
    {data Bin[2] view_1p2_25 rc_worst_25}
    {data Bin[1] view_1p2_25 rc_worst_25}
    {data Bin[0] view_1p2_25 rc_worst_25}
    {data Sum[15] view_1p2_25 rc_worst_25}
    {data Error[1] view_1p2_25 rc_worst_25}
    {data Error[0] view_1p2_25 rc_worst_25}
    {data FE_OFN14_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN13_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN12_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN11_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN10_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN9_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN8_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN7_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN6_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN5_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN4_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN3_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN2_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN1_n_0 view_1p2_25 rc_worst_25}
    {data FE_OFN0_n_0 view_1p2_25 rc_worst_25}
    {data FE_MDBN0_ view_1p2_25 rc_worst_25}
    {data A[15] view_1p2_25 rc_worst_25}
    {data A[14] view_1p2_25 rc_worst_25}
    {data A[13] view_1p2_25 rc_worst_25}
    {data A[12] view_1p2_25 rc_worst_25}
    {data A[11] view_1p2_25 rc_worst_25}
    {data A[10] view_1p2_25 rc_worst_25}
    {data A[9] view_1p2_25 rc_worst_25}
    {data A[8] view_1p2_25 rc_worst_25}
    {data A[7] view_1p2_25 rc_worst_25}
    {data A[6] view_1p2_25 rc_worst_25}
    {data A[5] view_1p2_25 rc_worst_25}
    {data A[4] view_1p2_25 rc_worst_25}
    {data A[3] view_1p2_25 rc_worst_25}
    {data A[2] view_1p2_25 rc_worst_25}
    {data A[1] view_1p2_25 rc_worst_25}
    {data A[0] view_1p2_25 rc_worst_25}
    {data B[15] view_1p2_25 rc_worst_25}
    {data B[14] view_1p2_25 rc_worst_25}
    {data B[13] view_1p2_25 rc_worst_25}
    {data B[12] view_1p2_25 rc_worst_25}
    {data B[11] view_1p2_25 rc_worst_25}
    {data B[10] view_1p2_25 rc_worst_25}
    {data B[9] view_1p2_25 rc_worst_25}
    {data B[8] view_1p2_25 rc_worst_25}
    {data B[7] view_1p2_25 rc_worst_25}
    {data B[6] view_1p2_25 rc_worst_25}
    {data B[5] view_1p2_25 rc_worst_25}
    {data B[4] view_1p2_25 rc_worst_25}
    {data B[3] view_1p2_25 rc_worst_25}
    {data B[2] view_1p2_25 rc_worst_25}
    {data B[1] view_1p2_25 rc_worst_25}
    {data B[0] view_1p2_25 rc_worst_25}
    {data n_0 view_1p2_25 rc_worst_25}
    {data n_2 view_1p2_25 rc_worst_25}
    {data n_3 view_1p2_25 rc_worst_25}
    {data n_4 view_1p2_25 rc_worst_25}
    {data n_5 view_1p2_25 rc_worst_25}
    {data n_6 view_1p2_25 rc_worst_25}
    {data n_7 view_1p2_25 rc_worst_25}
    {data n_8 view_1p2_25 rc_worst_25}
    {data n_9 view_1p2_25 rc_worst_25}
    {data n_10 view_1p2_25 rc_worst_25}
    {data n_11 view_1p2_25 rc_worst_25}
    {data n_12 view_1p2_25 rc_worst_25}
    {data n_13 view_1p2_25 rc_worst_25}
    {data n_14 view_1p2_25 rc_worst_25}
    {data n_15 view_1p2_25 rc_worst_25}
    {data n_16 view_1p2_25 rc_worst_25}
    {data n_17 view_1p2_25 rc_worst_25}
    {data n_18 view_1p2_25 rc_worst_25}
    {data n_19 view_1p2_25 rc_worst_25}
    {data n_20 view_1p2_25 rc_worst_25}
    {data n_21 view_1p2_25 rc_worst_25}
    {data n_22 view_1p2_25 rc_worst_25}
    {data n_23 view_1p2_25 rc_worst_25}
    {data n_24 view_1p2_25 rc_worst_25}
    {data n_25 view_1p2_25 rc_worst_25}
    {data n_26 view_1p2_25 rc_worst_25}
    {data n_27 view_1p2_25 rc_worst_25}
    {data n_28 view_1p2_25 rc_worst_25}
    {data n_29 view_1p2_25 rc_worst_25}
    {data n_30 view_1p2_25 rc_worst_25}
    {data n_31 view_1p2_25 rc_worst_25}
    {data n_32 view_1p2_25 rc_worst_25}
    {data n_33 view_1p2_25 rc_worst_25}
    {data n_34 view_1p2_25 rc_worst_25}
    {data n_35 view_1p2_25 rc_worst_25}
  }
}
