from pathlib import Path
import os
import struct
import torch
import numpy as np

# ---------------------------------------------------------------------
# File paths
# ---------------------------------------------------------------------
PATH_TO_PKG_FILE = "tb/unit/systolic_array/systolic_array_tb_pkg.sv"
ATALLA_ROOT = os.getenv("ATALLA_ROOT")
if ATALLA_ROOT is None:
    raise RuntimeError("ATALLA_ROOT env variable is not defined")
ATALLA_ROOT = Path(ATALLA_ROOT).expanduser().resolve()
PATH_TO_INPUT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_input.csv"
PATH_TO_EXPECTED_RESULT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_expected_result.csv"
PATH_TO_RESULT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_result.csv"

# ---------------------------------------------------------------------
# Systolic array params
# ---------------------------------------------------------------------
latency = 40
array_dim = 32
data_width = 16

# ---------------------------------------------------------------------
# Create tb package file
# ---------------------------------------------------------------------
def create_tb_pkg():
    with open(ATALLA_ROOT / PATH_TO_PKG_FILE, "w") as pkg:
        pkg.write("// This file is auto generated by scripts/systolic_array/systolic_array_tb.py \n\n")

        pkg.write(f"package systolic_array_tb_pkg;\n")
        pkg.write(f"// Local params contains path to input and output files for file reading\n")
        pkg.write(f"localparam string PATH_TO_PROJ = \"{ATALLA_ROOT}\";\n")
        pkg.write(f"localparam string PATH_TO_INPUT = \"{PATH_TO_INPUT}\";\n")
        pkg.write(f"localparam string PATH_TO_EXPECTED_RESULT = \"{PATH_TO_EXPECTED_RESULT}\";\n")
        pkg.write(f"localparam string PATH_TO_RESULT = \"{PATH_TO_RESULT}\";\n")
        pkg.write(f"\n")

        pkg.write(f"// Systolic array parameters\n")
        pkg.write(f"parameter int LATENCY = {latency};\n")
        pkg.write(f"parameter int ARRAY_DIM = {array_dim};\n")
        pkg.write(f"parameter int DATA_WIDTH = {data_width};\n")
        pkg.write(f"// Might need this for variable array size?\n")
        pkg.write(f"// parameter int ARRAY_WIDTH = {array_dim};\n")
        pkg.write(f"// parameter int ARRAY_HEIGHT = {array_dim};\n")

        pkg.write(f"endpackage\n")

# ---------------------------------------------------------------------
# Create tb test and expected output vectors
# ---------------------------------------------------------------------
def append_matrix(file_path, matrix):
    """
    Append a 2-D matrix to a CSV file.
    Each row becomes one CSV line.
    Values are written as hex (0x????).
    """

    # Convert torch tensor -> numpy
    if isinstance(matrix, torch.Tensor):
        if matrix.dtype in (torch.bfloat16, torch.float16):
            matrix = matrix.contiguous().view(torch.uint16).cpu().numpy()
        else:
            matrix = matrix.cpu().numpy()

    if not isinstance(matrix, np.ndarray):
        raise TypeError("matrix must be torch.Tensor or numpy.ndarray")

    if matrix.ndim != 2:
        raise ValueError("matrix must be 2-D")

    with open(file_path, "a", encoding="utf-8") as f:
        for r in range(matrix.shape[0]):
            row = ",".join(f"0x{int(x):04X}" for x in matrix[r])
            f.write(row + "\n")
        f.write("\n")


def gen_matrix(height, width, *, dtype="bf16", seed=None, scale=1.0, device="cpu", fill_value=None):
    """
    Generate a (height x width) matrix in BF16 or FP16.
    Generate in FP32, then cast (deterministic rounding)
    """

    if seed is not None:
        torch.manual_seed(seed)

    if dtype == "bf16":
        out_dtype = torch.bfloat16
    elif dtype == "fp16":
        out_dtype = torch.float16
    else:
        raise ValueError("dtype must be 'bf16' or 'fp16'")

    if fill_value is None:
        mat_f32 = torch.randn(height, width, dtype=torch.float32, device=device) * scale
        mat = mat_f32.to(out_dtype)
    else:
        mat_f32 = torch.full((height, width), float(fill_value), dtype=torch.float32, device=device)
        mat = mat_f32.to(out_dtype)

    return mat

def identity_matrix(height, width, *, dtype="bf16", device="cpu"):
    """
    Generate a (height x width) identity matrix in BF16 or FP16.
    Generate in FP32, then cast (deterministic rounding)
    Ones on the main diagonal up to min(height, width).
    """

    if dtype == "bf16":
        out_dtype = torch.bfloat16
    elif dtype == "fp16":
        out_dtype = torch.float16
    else:
        raise ValueError("dtype must be 'bf16', or 'fp16'")

    I_fp32 = torch.zeros(height, width, dtype=torch.float32, device=device)
    diag_len = min(height, width)

    for i in range(diag_len):
        I_fp32[i, i] = 1.0

    mat = I_fp32.to(out_dtype)

    return mat

def write_line(path, text):
    with open(path, "a") as f:
        f.write(text + "\n")

# ---------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------
if __name__ == "__main__":
    create_tb_pkg()

    Path(PATH_TO_INPUT).write_text("")
    Path(PATH_TO_EXPECTED_RESULT).write_text("")
    Path(PATH_TO_RESULT).write_text("")

    # Test 1
    A = gen_matrix(array_dim, array_dim, fill_value=0)
    write_line(PATH_TO_INPUT, "Test 1: Zero weight matrix")
    write_line(PATH_TO_INPUT, "Weight")
    append_matrix(PATH_TO_INPUT, A)

    B = gen_matrix(array_dim, array_dim)
    write_line(PATH_TO_INPUT, "Input")
    append_matrix(PATH_TO_INPUT, B)

    C = gen_matrix(array_dim, array_dim, fill_value=0)
    write_line(PATH_TO_INPUT, "Psum")
    append_matrix(PATH_TO_INPUT, C)

    # TODO: Replace the matrix multiplication with systolic array design simulation
    D = A @ B + C
    write_line(PATH_TO_EXPECTED_RESULT, "Test 1: Zero weight matrix")
    append_matrix(PATH_TO_EXPECTED_RESULT, D)

    # Test 2
    A = identity_matrix(array_dim, array_dim)
    write_line(PATH_TO_INPUT, "Test 2: identity weight matrix")
    write_line(PATH_TO_INPUT, "Weight")
    append_matrix(PATH_TO_INPUT, A)

    B = gen_matrix(array_dim, array_dim)
    write_line(PATH_TO_INPUT, "Input")
    append_matrix(PATH_TO_INPUT, B)

    C = gen_matrix(array_dim, array_dim, fill_value=0)
    write_line(PATH_TO_INPUT, "Psum")
    append_matrix(PATH_TO_INPUT, C)

    # TODO: Replace the matrix multiplication with systolic array design simulation
    D = A @ B + C
    write_line(PATH_TO_EXPECTED_RESULT, "Test 2: identity weight matrix")
    append_matrix(PATH_TO_EXPECTED_RESULT, D)