from pathlib import Path
import os
import struct
import torch
import numpy as np
import bf16_utils
import fp16_utils
import time
import sys
import argparse
import compare_result

# ---------------------------------------------------------------------
# File paths
# ---------------------------------------------------------------------
PATH_TO_PKG_FILE = "tb/unit/systolic_array/systolic_array_tb_pkg.sv"
ATALLA_ROOT = os.getenv("ATALLA_ROOT")
if ATALLA_ROOT is None:
    raise RuntimeError("ATALLA_ROOT env variable is not defined")
ATALLA_ROOT = Path(ATALLA_ROOT).expanduser().resolve()
PATH_TO_INPUT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_input.csv"
PATH_TO_EXPECTED_RESULT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_expected_result.csv"
PATH_TO_RESULT = ATALLA_ROOT / "scripts/systolic_array/systolic_array_tb_result.csv"

# ---------------------------------------------------------------------
# Systolic array params
# ---------------------------------------------------------------------
latency = 40
array_dim = 32
data_width = 16
dtype = "fp16"
seed = 777

gen_test_vectors = True
gen_pkg_file = True

# ---------------------------------------------------------------------
# Create tb package file
# ---------------------------------------------------------------------
def create_tb_pkg():
    print("Generating package file")
    with open(ATALLA_ROOT / PATH_TO_PKG_FILE, "w") as pkg:
        pkg.write("// This file is auto generated by scripts/systolic_array/systolic_array_tb.py \n\n")

        pkg.write(f"package systolic_array_tb_pkg;\n")
        pkg.write(f"// Local params contains path to input and output files for file reading\n")
        pkg.write(f"localparam string PATH_TO_PROJ = \"{ATALLA_ROOT}\";\n")
        pkg.write(f"localparam string PATH_TO_INPUT = \"{PATH_TO_INPUT}\";\n")
        pkg.write(f"localparam string PATH_TO_EXPECTED_RESULT = \"{PATH_TO_EXPECTED_RESULT}\";\n")
        pkg.write(f"localparam string PATH_TO_RESULT = \"{PATH_TO_RESULT}\";\n")
        pkg.write(f"\n")

        pkg.write(f"// Systolic array parameters\n")
        pkg.write(f"parameter int LATENCY = {latency};\n")
        pkg.write(f"parameter int ARRAY_DIM = {array_dim};\n")
        pkg.write(f"parameter int DATA_WIDTH = {data_width};\n")
        pkg.write(f"// Might need this for variable array size?\n")
        pkg.write(f"// parameter int ARRAY_WIDTH = {array_dim};\n")
        pkg.write(f"// parameter int ARRAY_HEIGHT = {array_dim};\n")

        pkg.write(f"endpackage\n")

# ---------------------------------------------------------------------
# Create tb test and expected output vectors
# ---------------------------------------------------------------------
def append_matrix(file_path, matrix):
    """
    Append a 2-D matrix to a CSV file.
    Each row becomes one CSV line.
    Values are written as hex (0x????).
    """

    if not isinstance(matrix, np.ndarray):
        raise TypeError("matrix must be numpy.ndarray")

    if matrix.ndim != 2:
        raise ValueError("matrix must be 2-D")

    with open(file_path, "a") as f:
        for r in range(matrix.shape[0]):
            row = ",".join(f"0x{int(x):04X}" for x in matrix[r])
            f.write(row + "\n")
        f.write("\n")


def gen_matrix(height, width, dtype="bf16", *, seed=None, scale=1.0,
               device="cpu", fill_value=None):
    """
    Returns (height x width) matrix as np.uint16 raw encodings
    suitable for HW simulation.
    """

    if seed is not None:
        torch.manual_seed(seed)

    # Select target floating dtype
    if dtype == "bf16":
        out_dtype = torch.bfloat16
    elif dtype == "fp16":
        out_dtype = torch.float16
    else:
        raise ValueError("dtype must be 'bf16' or 'fp16'")

    # Generate in FP32 first
    if fill_value is None:
        mat_f32 = torch.randn(height, width, dtype=torch.float32,
                              device=device) * float(scale)
    else:
        mat_f32 = torch.full((height, width), float(fill_value),
                             dtype=torch.float32, device=device)

    # Cast with deterministic rounding
    mat = mat_f32.to(out_dtype)

    # Reinterpret bits as uint16
    mat = mat.view(torch.uint16)

    # Convert to numpy uint16 for simulator
    return mat.cpu().numpy()

def identity_matrix(height, width, dtype="bf16", *, device="cpu"):
    """
    Returns a (height x width) identity matrix in BF16 or FP16.
    Generate in FP32, then cast (deterministic rounding)
    Ones on the main diagonal up to min(height, width).
    """

    if dtype == "bf16":
        out_dtype = torch.bfloat16
    elif dtype == "fp16":
        out_dtype = torch.float16
    else:
        raise ValueError("dtype must be 'bf16', or 'fp16'")

    I_fp32 = torch.zeros(height, width, dtype=torch.float32, device=device)
    diag_len = min(height, width)

    for i in range(diag_len):
        I_fp32[i, i] = 1.0

    mat = I_fp32.to(out_dtype)

    # Reinterpret bits as uint16
    mat = mat.view(torch.uint16)

    # Return NumPy uint16 for simulator
    return mat.cpu().numpy()

def gen_matrix_fill_col(height, width, dtype="bf16", *, col_index,
                        seed=None,
                        device="cpu", one_value=1.0):

    if seed is not None:
        torch.manual_seed(seed)

    # Select dtype
    if dtype == "bf16":
        out_dtype = torch.bfloat16
    elif dtype == "fp16":
        out_dtype = torch.float16
    else:
        raise ValueError("dtype must be 'bf16' or 'fp16'")

    if col_index < 0 or col_index >= width:
        raise ValueError("col_index must be within [0, width-1]")

    # Base matrix
    mat_f32 = torch.zeros((height, width),
                          dtype=torch.float32,
                          device=device)

    # Fill column
    mat_f32[:, col_index] = float(one_value)

    # Cast + reinterpret bits
    mat = mat_f32.to(out_dtype)
    mat = mat.view(torch.uint16)

    return mat.cpu().numpy()

def gen_matrix_fill_row(height, width, dtype="bf16", *, row_index,
                        seed=None,
                        device="cpu", one_value=1.0):

    if seed is not None:
        torch.manual_seed(seed)

    # Select dtype
    if dtype == "bf16":
        out_dtype = torch.bfloat16
    elif dtype == "fp16":
        out_dtype = torch.float16
    else:
        raise ValueError("dtype must be 'bf16' or 'fp16'")

    if row_index < 0 or row_index >= width:
        raise ValueError("col_index must be within [0, width-1]")

    # Base matrix
    mat_f32 = torch.zeros((height, width),
                          dtype=torch.float32,
                          device=device)

    # Fill column
    mat_f32[row_index, :] = float(one_value)

    # Cast + reinterpret bits
    mat = mat_f32.to(out_dtype)
    mat = mat.view(torch.uint16)

    return mat.cpu().numpy()

def write_line(path, text):
    with open(path, "a") as f:
        f.write(text + "\n")

def sim_val_from_bits(bits, dtype="bf16"):
    if dtype == "bf16":
        return bf16_utils.bf16_from_bits(bits)
    elif dtype == "fp16":
        return fp16_utils.fp16_from_bits(bits)
    raise ValueError("dtype must be 'bf16' or 'fp16'")

def sim_add_hw(a: np.uint16, b: np.uint16, dtype="bf16") -> np.uint16:
    if dtype == "bf16":
        return np.uint16(bf16_utils.bf16_add_hw(a, b))
    elif dtype == "fp16":
        return np.uint16(fp16_utils.fp16_add_hw(a, b))
    raise ValueError("dtype must be 'bf16' or 'fp16'")

def sim_mul_hw(a: np.uint16, b: np.uint16, dtype="bf16") -> np.uint16:
    if dtype == "bf16":
        return np.uint16(bf16_utils.bf16_mul_hw(a, b))
    elif dtype == "fp16":
        return np.uint16(fp16_utils.fp16_mul_hw(a, b))
    raise ValueError("dtype must be 'bf16' or 'fp16'")

def sim_adder_tree_hw(vec: np.ndarray, Psum: np.uint16, dtype="bf16") -> np.uint16:
    # vec: shape (K,), dtype uint16
    if vec.size == 0:
        return np.uint16(Psum)

    level = vec.astype(np.uint16, copy=False)

    # balanced reduction
    while level.size > 1:
        n = level.size
        m = n // 2

        nxt = np.empty((m + (n & 1),), dtype=np.uint16)

        # pairwise adds
        for i in range(m):
            nxt[i] = sim_add_hw(level[2*i], level[2*i + 1], dtype)

        # carry last if odd
        if n & 1:
            nxt[m] = level[-1]

        level = nxt

    return sim_add_hw(level[0], Psum, dtype)

def sim_MEISSA_col(A_row: np.ndarray, B_col: np.ndarray, Psum: np.uint16, dtype="bf16") -> np.uint16:
    # A_row, B_col: shape (K,), dtype uint16
    if A_row.shape != B_col.shape:
        raise ValueError(f"A_row and B_col must match shapes, got {A_row.shape} vs {B_col.shape}")
    if A_row.dtype != np.uint16 or B_col.dtype != np.uint16:
        raise TypeError("A_row and B_col must be np.uint16 arrays of raw bits")

    K = A_row.size
    vec = np.empty((K,), dtype=np.uint16)

    for i in range(K):
        vec[i] = sim_mul_hw(A_row[i], B_col[i], dtype)

    return sim_adder_tree_hw(vec, np.uint16(Psum), dtype)


def sim_MEISSA(weight: np.ndarray, input: np.ndarray, psum: np.ndarray, dtype="bf16") -> np.ndarray:
    # A: (M,K), B: (K,N), C: (M,N) all uint16 raw bits
    if dtype not in ("bf16", "fp16"):
        raise ValueError("dtype must be 'bf16' or 'fp16'")

    if weight.dtype != np.uint16 or input.dtype != np.uint16 or psum.dtype != np.uint16:
        raise TypeError("A, B, C must be np.uint16 arrays of raw bits")

    M, K = input.shape
    K2, N = weight.shape
    if K != K2:
        raise ValueError(f"Inner dims must match: input is {input.shape}, weight is {weight.shape}")
    if psum.shape != (M, N):
        raise ValueError(f"psum must be shape {(M, N)}, got {psum.shape}")

    D = np.empty((M, N), dtype=np.uint16)

    for r in range(M):
        A_row = input[r, :]
        for c in range(N):
            B_col = weight[:, c]
            D[r, c] = sim_MEISSA_col(A_row, B_col, C[r, c], dtype)

    return D

def progress_bar(iteration, total, width=40):
    percent = iteration / total
    filled = int(width * percent)
    bar = "#" * filled + "-" * (width - filled)

    sys.stdout.write(f"\r[{bar}] {percent*100:6.2f}% ({iteration}/{total})")
    sys.stdout.flush()

    if iteration == total:
        print()   # newline at end

# ---------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------
if __name__ == "__main__":

    test_total_num = 2
    test_num = 0

    if gen_pkg_file:
        create_tb_pkg()

    if gen_test_vectors:
        # Reset files
        Path(PATH_TO_INPUT).write_text("")
        Path(PATH_TO_EXPECTED_RESULT).write_text("")
        Path(PATH_TO_RESULT).write_text("")

        # # ---------------------------------------------------------------------
        # # Test 1
        # print("Generating test vectors")
        # A = gen_matrix(array_dim, array_dim, dtype, fill_value=0)
        # write_line(PATH_TO_INPUT, "Test 1: Zero weight matrix")
        # write_line(PATH_TO_INPUT, "Weight")
        # append_matrix(PATH_TO_INPUT, A)

        # B = gen_matrix(array_dim, array_dim, dtype)
        # write_line(PATH_TO_INPUT, "Input")
        # append_matrix(PATH_TO_INPUT, B)

        # C = gen_matrix(array_dim, array_dim, dtype, fill_value=0)
        # write_line(PATH_TO_INPUT, "Psum")
        # append_matrix(PATH_TO_INPUT, C)

        # test_num += 1
        # progress_bar(test_num, test_total_num)

        # D = sim_MEISSA(A, B, C, dtype)
        # write_line(PATH_TO_EXPECTED_RESULT, "Test 1: Zero weight matrix")
        # append_matrix(PATH_TO_EXPECTED_RESULT, D)

        # # ---------------------------------------------------------------------
        # # Test 2
        # A = identity_matrix(array_dim, array_dim, dtype)
        # write_line(PATH_TO_INPUT, "Test 2: identity weight matrix")
        # write_line(PATH_TO_INPUT, "Weight")
        # append_matrix(PATH_TO_INPUT, A)

        # B = gen_matrix(array_dim, array_dim, dtype)
        # write_line(PATH_TO_INPUT, "Input")
        # append_matrix(PATH_TO_INPUT, B)

        # C = gen_matrix(array_dim, array_dim, dtype, fill_value=0)
        # write_line(PATH_TO_INPUT, "Psum")
        # append_matrix(PATH_TO_INPUT, C)

        # D = sim_MEISSA(A, B, C, dtype)
        # write_line(PATH_TO_EXPECTED_RESULT, "Test 2: identity weight matrix")
        # append_matrix(PATH_TO_EXPECTED_RESULT, D)

        # test_num += 1
        # progress_bar(test_num, test_total_num)

        # # ---------------------------------------------------------------------
        # # Test 3
        # A = gen_matrix_fill_col(array_dim, array_dim, dtype, col_index=0)
        # write_line(PATH_TO_INPUT, "Test 3: one-hot column weight matrix")
        # write_line(PATH_TO_INPUT, "Weight")
        # append_matrix(PATH_TO_INPUT, A)

        # B = gen_matrix(array_dim, array_dim, dtype)
        # write_line(PATH_TO_INPUT, "Input")
        # append_matrix(PATH_TO_INPUT, B)

        # C = gen_matrix(array_dim, array_dim, dtype, fill_value=0)
        # write_line(PATH_TO_INPUT, "Psum")
        # append_matrix(PATH_TO_INPUT, C)

        # D = sim_MEISSA(A, B, C, dtype)
        # write_line(PATH_TO_EXPECTED_RESULT, "Test 3: one-hot column weight matrix")
        # append_matrix(PATH_TO_EXPECTED_RESULT, D)

        # test_num += 1
        # progress_bar(test_num, test_total_num)

        # # ---------------------------------------------------------------------
        # # Test 4
        # A = gen_matrix(array_dim, array_dim, dtype)
        # write_line(PATH_TO_INPUT, "Test 4: Non-zero Psum")
        # write_line(PATH_TO_INPUT, "Weight")
        # append_matrix(PATH_TO_INPUT, A)

        # B = gen_matrix(array_dim, array_dim, dtype)
        # write_line(PATH_TO_INPUT, "Input")
        # append_matrix(PATH_TO_INPUT, B)

        # C = gen_matrix(array_dim, array_dim, dtype)
        # write_line(PATH_TO_INPUT, "Psum")
        # append_matrix(PATH_TO_INPUT, C)

        # D = sim_MEISSA(A, B, C, dtype)
        # write_line(PATH_TO_EXPECTED_RESULT, "Test 4: Non-zero Psum")
        # append_matrix(PATH_TO_EXPECTED_RESULT, D)

        # test_num += 1
        # progress_bar(test_num, test_total_num)

        # ---------------------------------------------------------------------
        # Test 5
        A = gen_matrix(array_dim, array_dim, dtype)
        write_line(PATH_TO_INPUT, "Test 5: Input matrices back to back with zero psum")
        write_line(PATH_TO_INPUT, "Weight")
        append_matrix(PATH_TO_INPUT, A)

        B = gen_matrix(array_dim, array_dim, dtype)
        write_line(PATH_TO_INPUT, "Input")
        append_matrix(PATH_TO_INPUT, B)

        C = gen_matrix(array_dim, array_dim, dtype, fill_value=0)
        write_line(PATH_TO_INPUT, "Psum")
        append_matrix(PATH_TO_INPUT, C)

        B1 = gen_matrix(array_dim, array_dim, dtype)
        write_line(PATH_TO_INPUT, "Input")
        append_matrix(PATH_TO_INPUT, B1)

        C1 = gen_matrix(array_dim, array_dim, dtype, fill_value=0)
        write_line(PATH_TO_INPUT, "Psum")
        append_matrix(PATH_TO_INPUT, C1)

        D = sim_MEISSA(A, B, C, dtype)
        write_line(PATH_TO_EXPECTED_RESULT, "Test 5: Input matrices back to back")
        append_matrix(PATH_TO_EXPECTED_RESULT, D)

        D1 = sim_MEISSA(A, B1, C1, dtype)
        append_matrix(PATH_TO_EXPECTED_RESULT, D1)

        test_num += 1
        progress_bar(test_num, test_total_num)

        # ---------------------------------------------------------------------
        # Test 6
        A = gen_matrix(array_dim, array_dim, dtype)
        write_line(PATH_TO_INPUT, "Test 6: Input matrices back to back")
        write_line(PATH_TO_INPUT, "Weight")
        append_matrix(PATH_TO_INPUT, A)

        B = gen_matrix(array_dim, array_dim, dtype)
        write_line(PATH_TO_INPUT, "Input")
        append_matrix(PATH_TO_INPUT, B)

        C = gen_matrix(array_dim, array_dim, dtype, fill_value=1.0)
        write_line(PATH_TO_INPUT, "Psum")
        append_matrix(PATH_TO_INPUT, C)

        B1 = gen_matrix(array_dim, array_dim, dtype)
        write_line(PATH_TO_INPUT, "Input")
        append_matrix(PATH_TO_INPUT, B1)

        C1 = gen_matrix_fill_row(array_dim, array_dim, dtype, row_index=0)
        write_line(PATH_TO_INPUT, "Psum")
        append_matrix(PATH_TO_INPUT, C1)

        D = sim_MEISSA(A, B, C, dtype)
        write_line(PATH_TO_EXPECTED_RESULT, "Test 5: Input matrices back to back")
        append_matrix(PATH_TO_EXPECTED_RESULT, D)

        D1 = sim_MEISSA(A, B1, C1, dtype)
        append_matrix(PATH_TO_EXPECTED_RESULT, D1)

        test_num += 1
        progress_bar(test_num, test_total_num)

        # # ---------------------------------------------------------------------
        # # Random Tests
        # for i in range(6, test_total_num + 1):
        #     A = gen_matrix(array_dim, array_dim, dtype)
        #     write_line(PATH_TO_INPUT, f"Test {i}")
        #     write_line(PATH_TO_INPUT, "Weight")
        #     append_matrix(PATH_TO_INPUT, A)

        #     B = gen_matrix(array_dim, array_dim, dtype)
        #     write_line(PATH_TO_INPUT, "Input")
        #     append_matrix(PATH_TO_INPUT, B)

        #     C = gen_matrix(array_dim, array_dim, dtype)
        #     write_line(PATH_TO_INPUT, "Psum")
        #     append_matrix(PATH_TO_INPUT, C)

        #     D = sim_MEISSA(A, B, C, dtype)
        #     write_line(PATH_TO_EXPECTED_RESULT, f"Test {i}")
        #     append_matrix(PATH_TO_EXPECTED_RESULT, D)

        #     test_num += 1
        #     progress_bar(test_num, test_total_num)
    
    # compare_result.compare_results(PATH_TO_EXPECTED_RESULT, PATH_TO_RESULT)