`timescale 1ns/1ps

// 2-input FP16 Addition Testbench using Berkeley SoftFloat test vectors
// Test vectors generated by gen_testfloat2 (IEEE-754 compliant via softfloat)
//
// Generate test cases:
//   ./gen_testfloat2 -n 1000000 > testfloat_cases_2.csv
//
// Build & run (Verilator):
//   command to do it-verilator --binary --timing -j 0 -Wall \
//       add_fp16_tb_softfloat.sv add_fp16.sv left_shift.sv
//   ./obj_dir/Vadd_fp16_tb_softfloat

/* verilator lint_off UNUSEDSIGNAL */
module add_fp16_tb_softfloat;

    localparam PERIOD = 2;

    logic tb_clk;
    logic tb_nrst;

    always begin
        tb_clk = 1'b0;
        #(PERIOD/2.0);
        tb_clk = 1'b1;
        #(PERIOD/2.0);
    end

    logic [15:0] tb_a, tb_b;
    logic tb_start;
    logic [15:0] tb_result;
    logic tb_done;
    logic [15:0] exp;

    int pass_count, fail_count;

    add_fp16 dut (
        .clk(tb_clk),
        .nRST(tb_nrst),
        .start(tb_start),
        .stall(1'b0),
        .sub(1'b0),
        .fp1_in(tb_a),
        .fp2_in(tb_b),
        .fp_out(tb_result),
        .done(tb_done)
    );

    task automatic test_case(input logic [15:0] a, input logic [15:0] b);
        @(negedge tb_clk);
        tb_start = 0;
        tb_a = a;
        tb_b = b;
        @(negedge tb_clk);
        tb_start = 1;
    endtask

    function automatic logic is_nan(input logic [15:0] val);
        return (val[14:10] == 5'b11111) && (val[9:0] != 10'b0);
    endfunction

    function automatic logic is_zero(input logic [15:0] val);
        return (val[14:0] == 15'b0);
    endfunction

    task automatic check_case(input string casename, input logic [15:0] expected);
        logic match;
        if (is_nan(tb_result) && is_nan(expected))
            match = 1'b1;
        else if (is_zero(tb_result) && is_zero(expected))
            match = 1'b1;
        else
            match = (tb_result === expected);

        if (!match) begin
            $display("FAIL %s: A=%h B=%h Got=%h Exp=%h",
                     casename, tb_a, tb_b, tb_result, expected);
            fail_count++;
        end else begin
            $display("PASS %s | A=%h B=%h -> %h",
                     casename, tb_a, tb_b, tb_result);
            pass_count++;
        end
    endtask

    localparam logic [15:0] P_INF      = 16'b0_11111_0000000000;
    localparam logic [15:0] N_INF      = 16'b1_11111_0000000000;
    localparam logic [15:0] NAN        = 16'b0_11111_0100000000;
    localparam logic [15:0] P_ZERO     = 16'b0_00000_0000000000;
    localparam logic [15:0] N_ZERO     = 16'b1_00000_0000000000;
    localparam logic [15:0] ONE        = 16'b0_01111_0000000000;
    localparam logic [15:0] TWO        = 16'b0_10000_0000000000;
    localparam logic [15:0] N_ONE      = 16'b1_01111_0000000000;
    localparam logic [15:0] N_TWO      = 16'b1_10000_0000000000;
    localparam logic [15:0] MIN_SUB    = 16'b0_00000_0000000001;
    localparam logic [15:0] MAX_FINITE = 16'b0_11110_1111111111;

    integer fd;
    string header;
    logic [15:0] a, b, expected;

initial begin
    pass_count = 0;
    fail_count = 0;
    tb_nrst = 1'b0;
    tb_start = 1'b0;
    tb_a = 16'h0;
    tb_b = 16'h0;

    #(PERIOD);
    tb_nrst = 1;
    #(PERIOD);

    $display("--- Hardcoded 2-input Addition Cases ---");

    // 1 + 1 = 2
    test_case(ONE, ONE);
    exp = TWO;
    #(PERIOD * 2);
    check_case("1+1=2", exp);
    #(PERIOD);

    // 0 + 0 = 0
    test_case(P_ZERO, P_ZERO);
    exp = P_ZERO;
    #(PERIOD * 2);
    check_case("0+0=0", exp);
    #(PERIOD);

    // 1 + 0 = 1
    test_case(ONE, P_ZERO);
    exp = ONE;
    #(PERIOD * 2);
    check_case("1+0=1", exp);
    #(PERIOD);

    // 1 + (-1) = 0
    test_case(ONE, N_ONE);
    exp = P_ZERO;
    #(PERIOD * 2);
    check_case("1+(-1)=0", exp);
    #(PERIOD);

    // -2 + -2 = -4
    test_case(N_TWO, N_TWO);
    exp = 16'b1_10001_0000000000; // -4
    #(PERIOD * 2);
    check_case("-2+(-2)=-4", exp);
    #(PERIOD);

    // Inf + 1 = Inf
    test_case(P_INF, ONE);
    exp = P_INF;
    #(PERIOD * 2);
    check_case("Inf+1=Inf", exp);
    #(PERIOD);

    // +Inf + -Inf = NaN
    test_case(P_INF, N_INF);
    exp = NAN;
    #(PERIOD * 2);
    check_case("+Inf+(-Inf)=NaN", exp);
    #(PERIOD);

    // NaN + 1 = NaN
    test_case(NAN, ONE);
    exp = NAN;
    #(PERIOD * 2);
    check_case("NaN+1=NaN", exp);
    #(PERIOD);

    // DAZ: subnormal + 1 = 1
    test_case(MIN_SUB, ONE);
    exp = ONE;
    #(PERIOD * 2);
    check_case("sub+1=1 (DAZ)", exp);
    #(PERIOD);

    // Overflow: max + max = Inf
    test_case(MAX_FINITE, MAX_FINITE);
    exp = P_INF;
    #(PERIOD * 2);
    check_case("max+max=Inf", exp);
    #(PERIOD);

    $display("");
    $display("--- Berkeley SoftFloat Random Test Cases ---");

    fd = $fopen("testfloat_cases_2.csv", "r");
    if (fd == 0) begin
        $display("WARNING: Could not open testfloat_cases_2.csv");
        $display("Build & run: gcc -O2 -I berkeley-softfloat-3/source/include \\");
        $display("  -I berkeley-softfloat-3/build/Linux-x86_64-GCC \\");
        $display("  gen_testfloat2.c \\");
        $display("  berkeley-softfloat-3/build/Linux-x86_64-GCC/softfloat.a \\");
        $display("  -o gen_testfloat2");
        $display("Then: ./gen_testfloat2 -n 1000000 > testfloat_cases_2.csv");
    end else begin
        // Skip header
        void'($fgets(header, fd));

        while (!$feof(fd)) begin
            int ret;
            ret = $fscanf(fd, "%h,%h,%h\n", a, b, expected);
            if (ret != 3) continue;

            @(negedge tb_clk);
            tb_start = 1;
            tb_a = a;
            tb_b = b;

            @(negedge tb_clk);
            tb_start = 0;

            #(PERIOD);  // Wait 1 cycle for pipeline result

            if (is_nan(tb_result) && is_nan(expected)) begin
                pass_count++;
            end else if (is_zero(tb_result) && is_zero(expected)) begin
                pass_count++;
            end else if (tb_result !== expected) begin
                $display("FAIL: A=%h B=%h Got=%h Exp=%h", a, b, tb_result, expected);
                fail_count++;
            end else begin
                pass_count++;
            end
        end

        $fclose(fd);
    end

    $display("");
    $display("=== Test Summary ===");
    $display("PASSED: %0d", pass_count);
    $display("FAILED: %0d", fail_count);

    if (fail_count == 0)
        $display("ALL TESTS PASSED!");
    else
        $display("SOME TESTS FAILED!");

    $finish;
end

endmodule
