`timescale 1ps/1ps

module tb_sysarr_16_input_adder();

    // --- Parameters & Constants ---
    localparam NUM_INPUTS = 16;
    localparam CLK_PERIOD = 1000; // 1000 ps = 1 ns (1 GHz)
    localparam PIPE_DEPTH = 8;

    // Standard FP32 Test Values
    localparam logic [31:0] FP32_ZERO     = 32'h00000000;
    localparam logic [31:0] FP32_ONE      = 32'h3F800000; // 1.0
    localparam logic [31:0] FP32_NEG_ONE  = 32'hBF800000; // -1.0
    localparam logic [31:0] FP32_SIXTEEN  = 32'h41800000; // 16.0
    localparam logic [31:0] FP32_POS_INF  = 32'h7F800000; // +Inf
    localparam logic [31:0] FP32_NEG_INF  = 32'hFF800000; // -Inf
    localparam logic [31:0] FP32_NAN      = 32'h7FC00000; // Default NaN payload generated by RTL

    // --- Signals ---
    logic clk;
    logic nRST;
    logic [31:0] in_data [NUM_INPUTS];
    logic [31:0] out_data;

    // --- Flatten input array for instantiation ---
    logic [NUM_INPUTS-1:0][31:0] flat_in_data;
    always_comb begin
        for (int i = 0; i < NUM_INPUTS; i++) flat_in_data[i] = in_data[i];
    end

    // --- DUT Instantiation ---
    sysarr_16_input_fp_adder #(
        .NUM_INPUTS(NUM_INPUTS)
    ) dut (
        .clk(clk),
        .nRST(nRST),
        .in_data(flat_in_data),
        .out_data(out_data)
    );

    // --- Clock Generation (1 GHz) ---
    initial begin
        clk = 0;
        forever #(CLK_PERIOD / 2) clk = ~clk;
    end

    // --- Test Execution Task ---
    task run_test(input string name, input logic [31:0] test_vec [NUM_INPUTS], input logic [31:0] expected);
        // Apply inputs
        for (int i = 0; i < NUM_INPUTS; i++) begin
            in_data[i] = test_vec[i];
        end

        // Wait for pipeline latency (8 cycles)
        repeat(PIPE_DEPTH) @(posedge clk);
        #1; // Step slightly past the clock edge to safely read the registered output

        // Check result
        if (out_data == expected) begin
            $display("[PASS] %s | Got: %h", name, out_data);
        end else begin
            $error("[FAIL] %s | Expected: %h, Got: %h", name, expected, out_data);
        end
        
        // Push a cycle of zeros between tests to clear the pipe
        for (int i = 0; i < NUM_INPUTS; i++) in_data[i] = FP32_ZERO;
        @(posedge clk);
    endtask

    // --- Main Simulation Block ---
    logic [31:0] test_stimulus [NUM_INPUTS];

    initial begin
        $display("Starting 16-Input FP Adder Pipeline Simulation...");
        $display("-------------------------------------------------");
        
        // Initialize and Reset
        for (int i = 0; i < NUM_INPUTS; i++) in_data[i] = 0;
        nRST = 0;
        repeat(2) @(posedge clk);
        nRST = 1;
        repeat(2) @(posedge clk);

        // -------------------------------------------------------------------
        // Test 1: All Zeros
        // -------------------------------------------------------------------
        for (int i = 0; i < NUM_INPUTS; i++) test_stimulus[i] = FP32_ZERO;
        run_test("All Zeros", test_stimulus, FP32_ZERO);

        // -------------------------------------------------------------------
        // Test 2: Accumulate 16 ones (1.0 * 16 = 16.0)
        // -------------------------------------------------------------------
        for (int i = 0; i < NUM_INPUTS; i++) test_stimulus[i] = FP32_ONE;
        run_test("Accumulate sixteen 1.0s", test_stimulus, FP32_SIXTEEN);

        // -------------------------------------------------------------------
        // Test 3: Total Cancellation (8 * 1.0 + 8 * -1.0 = 0.0)
        // -------------------------------------------------------------------
        for (int i = 0; i < 8; i++) test_stimulus[i] = FP32_ONE;
        for (int i = 8; i < 16; i++) test_stimulus[i] = FP32_NEG_ONE;
        run_test("Total Cancellation to 0.0", test_stimulus, FP32_ZERO);

        // -------------------------------------------------------------------
        // Test 4: +Inf Domination (+Inf + 15 regular numbers = +Inf)
        // -------------------------------------------------------------------
        for (int i = 0; i < NUM_INPUTS; i++) test_stimulus[i] = FP32_ONE;
        test_stimulus[3] = FP32_POS_INF; // Inject +Inf into slot 3
        run_test("Positive Infinity Domination", test_stimulus, FP32_POS_INF);

        // -------------------------------------------------------------------
        // Test 5: The Inf Conflict (+Inf + -Inf = NaN)
        // -------------------------------------------------------------------
        for (int i = 0; i < NUM_INPUTS; i++) test_stimulus[i] = FP32_ZERO;
        test_stimulus[5] = FP32_POS_INF;
        test_stimulus[12] = FP32_NEG_INF;
        run_test("Inf Conflict (+Inf + -Inf)", test_stimulus, FP32_NAN);

        // -------------------------------------------------------------------
        // Test 6: NaN Propagation (NaN poisons the whole tree)
        // -------------------------------------------------------------------
        for (int i = 0; i < NUM_INPUTS; i++) test_stimulus[i] = FP32_ONE;
        test_stimulus[7] = FP32_NAN;
        run_test("NaN Propagation", test_stimulus, FP32_NAN);

        // -------------------------------------------------------------------
        $display("-------------------------------------------------");
        $display("Simulation Complete.");
        $finish;
    end

endmodule
