// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vadder_4input_tree32_tb.h for the primary calling header

#include "Vadder_4input_tree32_tb__pch.h"
#include "Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3.h"

VL_ATTR_COLD void Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3___ctor_var_reset(Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3___ctor_var_reset\n"); );
    Vadder_4input_tree32_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->clk = VL_RAND_RESET_I(1);
    vlSelf->nRST = VL_RAND_RESET_I(1);
    vlSelf->__PVT__safe_a = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__safe_b = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__safe_c = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__safe_d = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__a_daz = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__b_daz = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__c_daz = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__d_daz = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__exp_a = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_b = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_c = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_d = VL_RAND_RESET_I(8);
    vlSelf->__PVT__frac_a = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_b = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_c = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_d = VL_RAND_RESET_I(26);
    vlSelf->__PVT__sign_a = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_b = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_c = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_d = VL_RAND_RESET_I(1);
    vlSelf->__PVT__exp_p = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_m = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_r = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_n = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_x = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_y = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_mx = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_nx = VL_RAND_RESET_I(8);
    vlSelf->__PVT__frac_p = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_m = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_r = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_n = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_x = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_y = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_mx = VL_RAND_RESET_I(26);
    vlSelf->__PVT__frac_nx = VL_RAND_RESET_I(26);
    vlSelf->__PVT__sign_p = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_m = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_r = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_n = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_x = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_y = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_mx = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sign_nx = VL_RAND_RESET_I(1);
    vlSelf->__PVT__exp_x_eff = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_y_eff = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_mx_eff = VL_RAND_RESET_I(8);
    vlSelf->__PVT__exp_nx_eff = VL_RAND_RESET_I(8);
    vlSelf->__PVT__y_shift = VL_RAND_RESET_I(9);
    vlSelf->__PVT__m_shift = VL_RAND_RESET_I(9);
    vlSelf->__PVT__n_shift = VL_RAND_RESET_I(9);
    vlSelf->__PVT__safe_y_shift = VL_RAND_RESET_I(6);
    vlSelf->__PVT__safe_m_shift = VL_RAND_RESET_I(6);
    vlSelf->__PVT__safe_n_shift = VL_RAND_RESET_I(6);
    vlSelf->__PVT__x_mant = VL_RAND_RESET_Q(59);
    vlSelf->__PVT__y_shifted = VL_RAND_RESET_Q(59);
    vlSelf->__PVT__m_shifted = VL_RAND_RESET_Q(59);
    vlSelf->__PVT__n_shifted = VL_RAND_RESET_Q(59);
    vlSelf->__PVT__y_mant_base = VL_RAND_RESET_Q(59);
    vlSelf->__PVT__m_mant_base = VL_RAND_RESET_Q(59);
    vlSelf->__PVT__n_mant_base = VL_RAND_RESET_Q(59);
    vlSelf->__PVT__sticky_y = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sticky_m = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sticky_n = VL_RAND_RESET_I(1);
    vlSelf->__PVT__y_op = VL_RAND_RESET_I(1);
    vlSelf->__PVT__m_op = VL_RAND_RESET_I(1);
    vlSelf->__PVT__n_op = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_nan_any = VL_RAND_RESET_I(1);
    vlSelf->__PVT__special_case = VL_RAND_RESET_I(1);
    vlSelf->__PVT__any_pos_inf = VL_RAND_RESET_I(1);
    vlSelf->__PVT__any_neg_inf = VL_RAND_RESET_I(1);
    vlSelf->__PVT__special_result = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__st1_a_e = VL_RAND_RESET_I(8);
    vlSelf->__PVT__st1_a_s = VL_RAND_RESET_I(1);
    vlSelf->__PVT__st1_align_sticky = VL_RAND_RESET_I(1);
    vlSelf->__PVT__st1_special_case = VL_RAND_RESET_I(1);
    vlSelf->__PVT__st1_special_result = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__st1_sum_vec = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__st1_carry_vec = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__st1_hot_ones = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(65, vlSelf->__PVT__raw_sum);
    vlSelf->__PVT__mag_sum = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__res_sign = VL_RAND_RESET_I(1);
    vlSelf->__PVT__st2_exp_base = VL_RAND_RESET_I(8);
    vlSelf->__PVT__st2_sum_mag = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__st2_spec_res = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__st2_res_sign = VL_RAND_RESET_I(1);
    vlSelf->__PVT__st2_sticky = VL_RAND_RESET_I(1);
    vlSelf->__PVT__st2_special = VL_RAND_RESET_I(1);
    vlSelf->__PVT__lzd_scan = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__lead_zeros = VL_RAND_RESET_I(6);
    vlSelf->__PVT__norm_val = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__raw_mant = VL_RAND_RESET_I(26);
    vlSelf->__PVT__final_mant = VL_RAND_RESET_I(26);
    vlSelf->__PVT__rounded_mant_int = VL_RAND_RESET_I(27);
    vlSelf->__PVT__final_exp_calc = VL_RAND_RESET_I(11);
    vlSelf->__PVT__guard_bit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__round_bit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__sticky_bit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__round_up = VL_RAND_RESET_I(1);
    vlSelf->__PVT__l_bit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__result_out = VL_RAND_RESET_Q(35);
    vlSelf->__PVT__op_x = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__op_y = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__op_m = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__op_n = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__csa_s1 = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__csa_c1 = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__csa_s2 = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__csa_c2 = VL_RAND_RESET_Q(63);
    vlSelf->__PVT__stage3_logic__DOT__unnamedblk1__DOT__i = 0;
}
