// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VADDER_4INPUT_TREE32_TB__SYMS_H_
#define VERILATED_VADDER_4INPUT_TREE32_TB__SYMS_H_  // guard

#include "verilated.h"
#include "verilated_vcd_c.h"

// INCLUDE MODEL CLASS

#include "Vadder_4input_tree32_tb.h"

// INCLUDE MODULE CLASSES
#include "Vadder_4input_tree32_tb___024root.h"
#include "Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3.h"
#include "Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1.h"

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)Vadder_4input_tree32_tb__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vadder_4input_tree32_tb* const __Vm_modelp;
    bool __Vm_dumping = false;  // Dumping is active
    VerilatedMutex __Vm_dumperMutex;  // Protect __Vm_dumperp
    VerilatedVcdC* __Vm_dumperp VL_GUARDED_BY(__Vm_dumperMutex) = nullptr;  /// Trace class for $dump*
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vadder_4input_tree32_tb___024root TOP;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__10__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__11__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__12__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__13__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__14__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__15__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__16__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__17__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__18__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__19__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__1__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__20__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__21__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__22__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__23__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__24__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__25__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__26__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__27__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__28__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__29__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__2__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__30__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__31__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__3__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__4__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__5__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__6__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__7__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__8__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_sysarr_4_input_fp_adder__pi3 TOP__adder_4input_tree32_tb__DOT__dut__DOT__gen_accum_stages__BRA__9__KET____DOT__stage_inst;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__0__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__10__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__11__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__12__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__13__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__14__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__15__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__16__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__17__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__18__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__19__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__1__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__20__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__21__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__22__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__23__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__24__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__25__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__26__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__27__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__28__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__29__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__2__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__30__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__31__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__3__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__4__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__5__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__6__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__7__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__8__KET__;
    Vadder_4input_tree32_tb_systolic_array_4_input_adder_if__pi1 TOP__adder_4input_tree32_tb__DOT__dut__DOT__ifc__BRA__9__KET__;

    // CONSTRUCTORS
    Vadder_4input_tree32_tb__Syms(VerilatedContext* contextp, const char* namep, Vadder_4input_tree32_tb* modelp);
    ~Vadder_4input_tree32_tb__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
    void _traceDump();
    void _traceDumpOpen();
    void _traceDumpClose();
};

#endif  // guard
