[book]
authors = ["Sooraj Chetput", "Timothy Hein", "Malcolm Mcclymont", "Fan Jing Hoon", "Rishikesh Bathina", "Akshath Raghav Ravikiran"]
language = "en"
src = "src"
title = "Atalla AIHW Documentation"
